services:
  earscopeweb-backend:
    image: earscopeweb-backend:latest
    container_name: earscopeweb-backend
    build: 
      context: ./backend
    ports:
      - "8010:8010"
    networks:
      - earscopeweb-network
      - mysql-network
    restart: unless-stopeed

  earscopeweb-frontend:
    image: earscopeweb-frontend:latest
    container_name: earscopeweb-frontend
    build: 
      context: ./frontend
    ports:
      - "8011:8080"
    networks:
      - earscopeweb-network
    restart: unless-stopeed

networks:
  earscopeweb-network:
    name: earscopeweb-network
    driver: bridge

  mysql-network:
    name: mysql-network
    external: true

    