services:
  earscopeweb-backend:
    image: earscopeweb-backend:latest
    container_name: earscopeweb-backend
    build: 
      context: ./backend
    ports:
      - "8010:8010"
    networks:
      - earscopeweb-network
      - mysql-network
      - nginx-network
    restart: unless-stopped
    volumes:
      - /var/www/log/earscopeweb-backend/storage/logs:/app/storage/logs # Sinkronisasi log ke host
      - /var/www/earscopeweb-backend/storage/app/private:/app/storage/app/private # Sinkronisasi storage

  earscopeweb-frontend:
    image: earscopeweb-frontend:latest
    container_name: earscopeweb-frontend
    build: 
      context: ./frontend
    ports:
      - "8011:8080"
    networks:
      - earscopeweb-network
      - nginx-network
    restart: unless-stopped

networks:
  earscopeweb-network:
    name: earscopeweb-network
    driver: bridge

  mysql-network:
    name: mysql-network
    external: true

  nginx-network:
    name: nginx-network
    external: true
